my first commit
kudinov-fedor/python_at_2021 pull request #15
Opened 2024-04-07 21:14 UTC by inna-honcharenko

2024-04-08 05:55 UTC, kudinov-fedor requested changes
name of module should stick to python naming convention of variables,

only letters numbers and underscore are allowed

2024-04-30 19:52 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_check_password.py
> +    assert check_password(password)
duplicate

2024-04-30 19:53 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_check_password.py
> +    assert not check_password("AAAAAAA1")
can use parametrize for  65 - 78 tests

2024-04-30 19:53 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_check_password.py
> +    assert check_password(f"1AAAAAAa{letter}")
there shoould be empty line at end of file

2024-04-30 19:53 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_not_reliable_function.py
> +
1 and only 1 empty line at end of file

2024-04-30 19:54 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_not_reliable_function.py
> +        not_reliable()
can use parametrize for tests 27 - 33

2024-04-30 19:54 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_not_reliable_function_2.py
> +    mocker.patch(__name__ + ".random", return_value=0.5)
nice

2024-04-30 19:55 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_not_reliable_function_2.py
> +
1 and only 1 empty line at end of file

2024-04-30 19:55 UTC, fkudinov-mn commented on tests/innahoncharenko/homework_1/test_use_config.py
> +        if_debug_on()
missing empty line at end of file

2024-04-30 19:56 UTC, kudinov-fedor approved these changes

2024-05-04 11:11 UTC, merged