hw1_check_pass
kudinov-fedor/python_at_2021 pull request #16
Opened 2024-04-09 01:08 UTC by KhrystynaTkachyk

@kudinov-fedor

2024-04-09 06:15 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("abc", False),                                         #check pwd < 8 symbols
put space after # : 

# check pwd < 8 symbols

2024-04-09 06:18 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +        assert check_password(pwd1) == res1
you do not need here 2nd param in parametrize since it is always the same:

parametrize for 1 param will look like this:

`@pytest.mark.parametrize("pwd1", [
    "sdfjJLsj123!@#sdfjJLsj123!@#sd",               #catch error for pwd = 30 symbols exactly
    "ssdfjJLsj1.,=",                             #catch error for ",.=" not being considered as symbols
    "sdfjJLsj4!",                                   #catch error for "4" not being considered as number
    "jTEST5)=",                                     #catch error for 'j' is not listed in lowercase letters
    "abcLLL3$"                                      #catch error for 'L' is not listed in uppercase letters
])
def test_error(pwd1):
    with pytest.raises(AssertionError):
        assert check_password(pwd1) == True
        # OR
        assert check_password(pwd1)

2024-04-09 06:19 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +        assert check_password(pwd1) == res1
but here error is risen not by function but by you in test
you can try to pass INT into function and check if it works or fails

2024-04-09 06:25 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("abcLLL3$", True)                                      #catch error for 'L' is not listed in uppercase letters
but what if error with other letter, can you suggest exhaustive test which will cover all letters

2024-04-09 06:25 UTC, kudinov-fedor commented on tests/khrystynatk/hw1_khr_check_password.py
> +print("All checks passed")
remove lines 31, 33

2024-04-09 06:26 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("abc", False),                                         #check pwd < 8 symbols
"abc"     is not a boundary value, and it is not pure length test, it can fail due to missing letter or spec symbol

2024-04-09 06:28 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("!@#$%^&*()", False),                                  #check symbols only
try reverse logic :
- check password without letters
- check password without numbers 
- check ...

test 1 thing at a time, tests will be more clear

2024-04-10 07:15 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("   A1^a   ", True)  # check spaces are counted as chars
I would probably expect False in such case,  i.e. ignore spaces at start and end, so that password is only 4 chars long

2024-04-10 07:19 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +            expected = res1
expected is always res1

2024-04-10 07:20 UTC, kudinov-fedor requested changes
hard to understand what you try to achieve with test_lower_upper_case test

2024-04-10 07:20 UTC, kudinov-fedor commented on tests/khrystynatk/hw1_khr_check_password.py
> +#
there should be empty line at end
try to use flake8 it can advise changes required to match expected codestyle

2024-04-10 07:21 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +@pytest.mark.skip(reason="not implemented")
is it skipped just to check skip mark ?

2024-04-10 07:22 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +    ("aaa123$%", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", False)
these cases can actually be n=moved to test_check_pass test

2024-04-10 20:28 UTC, KhrystynaTkachyk commented
@kudinov-fedor commited new changes

2024-04-11 09:29 UTC, kudinov-fedor commented on tests/khrystynatk/test_hw1_khr_check_password.py
> +        assert check_password(res1)
you can try gather all errors , in your case test will fail on first check
though it will do the job, but you will not see the whole picture

2024-04-11 09:29 UTC, kudinov-fedor approved these changes

2024-04-11 09:47 UTC, merged