tests for check_password function
kudinov-fedor/python_at_2021 pull request #18
Opened 2024-04-10 11:43 UTC by Greta-mart

2024-04-10 11:59 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +
2 empty lines between objects in module

2024-04-10 12:00 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +    pytest.param('qwerty8@', id='Password without capital letter, but with nuber and special character'),
try to reduce id names, its hard to read

e.g.:

no upper letters
no numbers
too short
too long

2024-04-10 12:01 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +    pytest.param('Q8@e', id='Password with less then 8 symbols'),
try to test boundary cases.   

7 symbols, 8, 30, 31

2024-04-10 12:04 UTC, kudinov-fedor approved these changes

2024-04-13 09:05 UTC, Greta-mart commented on tests/threc/hw_password/test_password.py
> +        assert check_password(res) is False
removed parametrize

2024-04-13 09:05 UTC, Greta-mart commented on tests/threc/hw_password/test_password.py
> +
Added two lines

2024-04-13 09:58 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +
not here, there should not be empty lines between function and decorator
use flake8 it can show warnings

2024-04-13 09:59 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +@pytest.mark.negative()
call is not required

@pytest.mark.negative

2024-04-13 09:59 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +
2 empty lines between imports and function

2024-04-13 10:00 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +
2 empty lines between functions

2024-04-13 10:00 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +def test_password_negative(res):
no empty line between decorator and function

2024-04-13 10:00 UTC, fkudinov-mn commented on tests/threc/hw_password/test_password.py
> +# Password with integer value instead of string
move comment to docstring of a function

2024-04-13 10:03 UTC, fkudinov-mn requested changes
codestyle should be fixed

2024-04-13 10:03 UTC, kudinov-fedor requested changes
-

2024-04-13 11:27 UTC, kudinov-fedor commented on tests/threc/not_reliable/not_reliable_function.py
> +    assert res == 0.6
function with tests should start with 'test_' prefix, so that pytest could gather these tests

2024-04-13 11:28 UTC, kudinov-fedor commented on tests/threc/not_reliable/test_not_reliable_function.py
> +    assert not_reliable() == 2
you can group these 3 tests into parametrize

2024-04-13 11:29 UTC, kudinov-fedor commented on tests/threc/not_reliable/test_not_reliable_function_2.py
> +    assert not_reliable() == 0.6
you can group positive tests into parametrize

2024-04-13 11:29 UTC, kudinov-fedor approved these changes

2024-04-13 11:34 UTC, kudinov-fedor commented on tests/threc/not_reliable/not_reliable_function.py
> +    mocker.patch('random.random', return_value=0.6)
you should not use patch like that !!!
patch is from UNITTEST and  pytest does not revert these changes,
better to check it , weather this patch is still applied for next tests


you should use either mocker.patch.object

OR

patch as context manager

```
def test_res_more_0_5(mocker):
    with mocker.patch('random.random', return_value=0.6): 
        res = not_reliable()
        assert res == 0.6
```

2024-04-13 11:34 UTC, kudinov-fedor requested changes
retest mocker.patch

2024-04-13 11:40 UTC, kudinov-fedor commented on tests/threc/not_reliable/test_not_reliable_function.py
> +    mocker.patch('random.random', return_value=0.5)
you can mock as this, module is a singletone in python - single object with global access

import random
mocker.patch.object(random, 'random', return_value=0.5)

2024-04-13 20:44 UTC, kudinov-fedor commented on tests/threc/not_reliable/test_not_reliable_function.py
> +])
@pytest.mark.parametrize("value", [0.5, 0.6, 2])

2024-04-13 20:44 UTC, kudinov-fedor approved these changes

2024-04-13 20:52 UTC, merged