Home work 3 Locators
kudinov-fedor/python_at_2021 pull request #43
Opened 2024-04-18 19:06 UTC by YanaPokulita

2024-04-18 19:18 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    shoppingCart = (By.CSS_SELECTOR, ".primary_header .shopping_cart_container")
python naming conventions usually are:

some_var_name
SOME_CONSTANT_NAME
SomeClassName

2024-04-18 19:20 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +class ForConfTest:
locators should not care, what file uses them, they should represent web pages , and give understanding on what web page or in what element on that page they are located

2024-04-18 19:21 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    FinishBtn = (By.CSS_SELECTOR, ".cart_footer .cart_button[data-test='finish'")
its simply by id

(By.CSS_SELECTOR, "#finish")

2024-04-18 19:21 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    btnContinue = (By.CSS_SELECTOR, ".checkout_buttons .submit-button[name='continue'")
locator not closed appropriately with ]

2024-04-18 19:22 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    FirstName = (By.CSS_SELECTOR, ".form_group .form_input[placeholder='First Name'")
rely on ID

(By.CSS_SELECTOR, "#first-name")

2024-04-18 19:23 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    CartItems = (By.XPATH, ".//*[@class='cart_item']")
use contains to rely on class name using xpath

2024-04-18 19:23 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    shoppingCartBadge = (By.CSS_SELECTOR, ".shopping_cart_link .shopping_cart_badge[data-test='shopping-cart-badge']")
this is how it looks if to translate from xpath to css selector

(By.CSS_SELECTOR, ".shopping_cart_badge")

2024-04-18 19:24 UTC, kudinov-fedor requested changes
rework locators

2024-04-18 19:44 UTC, YanaPokulita commented on tests/yana_pokulita/locators.py
> +class ForConfTest:
tbh not sure what this means

2024-04-19 05:51 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    ShoppingCart = (By.CSS_SELECTOR, ".primary_header .shopping_cart_container")
need to fix

2024-04-19 05:52 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    CartItems = (By.XPATH, ".//*[@class='cart_item']")
need to fix

2024-04-19 05:52 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    CheckOutBtn = (By.CSS_SELECTOR, ".cart_footer .checkout_button[name='checkout']")
need to fix

2024-04-19 05:52 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    Remove1stItemBtn = (By.XPATH, "//*[@id='remove-sauce-labs-backpack']")
add tag name to xpath

2024-04-19 05:53 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    FinishBtn = (By.CSS_SELECTOR, "#finish")
add also xpath as a comment

2024-04-19 05:59 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +class ForConfTest:
you should have locators grouped as per page and as per page elements, but not as per project files. e.g:


```
class LoginPage:
  TXT_NAME = ...
  TXT_PASSWORD = ...
  BTN_SUBMIT = ...


class CatalogPage:
    
    CART_ICON = ...
    
    class Item:
         SELF = ...        # locator for all items in table
         BTN_TO_CART = ...     # relative locator from SELF
         TXT_PRICE = ....




# usage

items = session.find_elements(*CatalogPage.Item.SELF)
items[3].find_element(*CatalogPage.Item.BTN_TO_CART).click()
```




you do not need to see the page, locators suggest you how page looks like, and look like elements tree

2024-04-19 06:00 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    Element3 = (By.CSS_SELECTOR, ".pricebar .btn_inventory")
why you have identical locators here

2024-04-19 06:01 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    Element1 = (By.CSS_SELECTOR, ".pricebar .btn_inventory")
provide identical xpath locator, 
locators do not match

2024-04-19 17:07 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    ShoppingCart = (By.CSS_SELECTOR, ".shopping_cart_container")
ShoppingCart = (By.CSS_SELECTOR, "#shopping_cart_container")

2024-04-19 17:07 UTC, fkudinov-mn commented on tests/yana_pokulita/locators.py
> +    CheckOutBtn = (By.CSS_SELECTOR, ".checkout_button[name='checkout']")
(By.CSS_SELECTOR, "#checkout")

2024-04-19 17:28 UTC, YanaPokulita commented on tests/yana_pokulita/locators.py
> +    CheckOutBtn = (By.CSS_SELECTOR, ".checkout_button[name='checkout']")
changed to suggested

2024-04-19 17:28 UTC, YanaPokulita commented on tests/yana_pokulita/locators.py
> +    ShoppingCart = (By.CSS_SELECTOR, ".shopping_cart_container")
changed to suggested

2024-04-19 17:38 UTC, kudinov-fedor commented on tests/yana_pokulita/locators.py
> +    CartItems = (By.XPATH, ".//*[@class='cart_item']")
CartItems = (By.XPATH, ".//*[contains(@class, 'cart_item')]")

2024-04-19 17:38 UTC, kudinov-fedor approved these changes

2024-04-19 17:40 UTC, kudinov-fedor commented on tests/yana_pokulita/locators.py
> +    Element = (By.CSS_SELECTOR, ".pricebar button")
from name completely not clear that it is add to cart button

2024-04-19 17:41 UTC, kudinov-fedor commented on tests/yana_pokulita/locators.py
> +    Elements = (By.XPATH, "//div[contains(@class, 'inventory_list')]//div[contains(@class, 'inventory_item_description')]")
its not elements - its element, all depends on how you use it

.find_element(*Elements)
.find_elements(*Elements)

2024-04-19 17:41 UTC, kudinov-fedor approved these changes

2024-04-19 17:44 UTC, kudinov-fedor approved these changes

2024-04-19 18:44 UTC, merged